window:
  width: 1280
  height: 720
  vsync: true

light:
  position: [1.2, 1.0, 2.0]
  ambient: [0.05, 0.05, 0.05]
  diffuse: [0.6, 0.6, 0.6]
  specular: [1.0, 1.0, 1.0]

camera:
  position: [0.0, 0.0, 3.0]
  worldUp: [0.0, 1.0, 0.0]
  front: [0.0, 0.0, -1.0]
  yaw: -90.0
  pitch: 0.0
  speed: 2.5
  sensitivity: 0.1
  fov: 75.0
  near: 0.1
  far: 100.0

model: 
  path: ./assets/models/nanosuit/nanosuit.obj
  size: 2.0